apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hornet-set
  labels:
    source: one-click-tangle
spec:
  serviceName: hornet-rest
  replicas: 1
  selector:
    matchLabels:
      app: hornet
  template:
    metadata:
      labels:
        app: hornet
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: create-volumes
        image: busybox
        command:
            - sh
            - -c
        args:
            - >-
                mkdir -p /ledger/peering &&
                cp /app/peering.json /ledger/peering/peering.json &&
                mkdir -p /ledger/mainnetdb &&
                mkdir -p /ledger/snapshots &&                 
                mkdir -p /ledger/p2pstore &&
                chown -R 65532:65532 /ledger
        volumeMounts:
            - mountPath: /ledger
              name: hornet-ledger
            - name: configuration
              mountPath: /app/peering.json
              subPath: peering.json
            - name: private-key
              mountPath: /app/p2pstore/identity.key
              subPath: private_key 
      containers:
      - name: hornet
        image: gohornet/hornet:1.1.3
        envFrom:
        - secretRef:         
            name: hornet-secret
            optional: false
        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
        workingDir: /app
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: 14265
          initialDelaySeconds: 55
        livenessProbe:
          httpGet:
            path: /api/v1/info
            port: 14265
          initialDelaySeconds: 60
        ports:
        - name: gossip
          protocol: TCP
          containerPort: 15600
        - name: autopeering
          protocol: UDP
          containerPort: 14626
        - name: rest
          protocol: TCP
          containerPort: 14265
        - name: dashboard
          protocol: TCP
          containerPort: 8081
        volumeMounts:
        - name: configuration
          mountPath: /app/config.json
          subPath: config.json
        - name: private-key
          mountPath: /app/p2pstore/identity.key
          subPath: private_key
        - name: hornet-ledger
          subPath: peering/peering.json
          mountPath: /app/peering.json
        - name: hornet-ledger
          subPath: mainnetdb
          mountPath: /app/mainnetdb
        - name: hornet-ledger
          subPath: p2pstore
          mountPath: /app/p2pstore
        - name: hornet-ledger
          subPath: snapshots
          mountPath: /app/snapshots/mainnet
      volumes:
      - name: configuration 
        configMap:
          name: hornet-config
      - name: private-key
        secret:
          secretName: hornet-private-key
  volumeClaimTemplates: 
    - metadata: 
        name: hornet-ledger
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 20Gi
